### PR TITLE
Fix transparent status bar background

### PR DESCRIPTION
**Pull request by tnev**
- table view cells will no longer show up under the status bar when
scrolling

### CODE REVIEW

**Comment by guillermomuntaner** [comment]
Can you provide screenshots of the effect and the fix please? Thank you.

**Comment by tnev** [comment]
You'll see that without the fix the table views' content extend past the top of the navigation bar.

Album View Controller without fix:

img_2764

Grid View Controller without fix:

img_2765

Album View Controller with fix:

img_2767

Grid View Controller with fix:

img_2768

**Comment by guillermomuntaner** [comment]
Ok i see the problem and the fix. You know how this works with the Popover mode?

**Comment by tnev** [comment]
As far as I can tell the popover was working as intended before this fix and it isn't affected by this fix.

**Comment by guillermomuntaner** [comment]
You mixed things in this pull request with the last commit.

**Comment by tnev** [comment]
Sorry about that, mixed up my branches, I reverted all unintentional commits if you still want to merge this.

**Comment by guillermomuntaner** [comment]
Yes, thank you!

**Pull request merged**
