### PR TITLE
Single Selection, Font/Color Customisation, Photo Taking, Custom Button Titles

### PR DESCRIPTION
**Pull request by krider2010**
I’ve made many changes here to support my needs. Each is in an individual checkin. Feel free to ask for any of those on their own and I can do a PR, or take all of the contributions :)

### CODE REVIEW

**Comment by guillermomuntaner** [comment]
Will check the PR asap. Most of the optional customizations look fine. Need to test the camera flow, will check!

Thank you for such an extensive push.

**Comment by jjxtra** [comment]
This going to get merged ever?

**Comment by guillermomuntaner** [comment]
I dont have time to test. Code looks nice so im going to just merge. If anyone has trouble becouse of it, just comment!

**Comment by krider2010** [comment]
It is being used in an app with end users, with pretty much all the extensions I added enabled and has been working well for us if that helps. Thanks for merging! :+1:

**Comment by guillermomuntaner** [comment]
Thanks for the comment! As i said the code looks good but ive been out of IOS dev for a while and dont have time for testing. Ty for such a great improvement!

**Pull request merged**
